[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000210589AE240>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/58842d2c2824b0dbf8b4f08dc9d3c1ed
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000210589AF770>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/58842d2c2824b0dbf8b4f08dc9d3c1ed
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000210589AF8F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/58842d2c2824b0dbf8b4f08dc9d3c1ed