[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020ABF39FA10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/672f348ef65bc1a40cb2d70e91828df1
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020ABF3D4680>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/672f348ef65bc1a40cb2d70e91828df1
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020ABF3D5D90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/672f348ef65bc1a40cb2d70e91828df1