[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001EE579ADB80>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/edc5c43e-b9f9-4940-b6d0-78923f20554b
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001EE5796A180>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/edc5c43e-b9f9-4940-b6d0-78923f20554b
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001EE579AF740>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/edc5c43e-b9f9-4940-b6d0-78923f20554b