[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002873AEFEFC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/4500c34c-a44f-4d63-a0dd-80a2d55f9f97
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002873AEFF7A0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/4500c34c-a44f-4d63-a0dd-80a2d55f9f97
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002873AEFF950>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/4500c34c-a44f-4d63-a0dd-80a2d55f9f97