[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000199F9C94A70>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/9fbbcc3529c673f756b28dc98f984de1
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000199F9E32FC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/9fbbcc3529c673f756b28dc98f984de1
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000199F9E320F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/9fbbcc3529c673f756b28dc98f984de1