[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023B2C41EEA0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/0bc821913a1ddd815e3b13d68052d812
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023B2C3D9280>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/0bc821913a1ddd815e3b13d68052d812
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023B2C41F380>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/0bc821913a1ddd815e3b13d68052d812