[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000116F275F590>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/777f46c3cddf8f1be18fcf2e67a32288
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000116F20F1070>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/777f46c3cddf8f1be18fcf2e67a32288
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000116F275F620>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/777f46c3cddf8f1be18fcf2e67a32288