[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020ABF3D4530>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/7fda1b492f24b1a324c87f338979215f
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020ABF3D4C50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/7fda1b492f24b1a324c87f338979215f
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020ABF3D4EF0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/7fda1b492f24b1a324c87f338979215f