[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022D45A1E630>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/a6c86a5850e40bb9ce5527c870fbafd5
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022D459E1430>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/a6c86a5850e40bb9ce5527c870fbafd5
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022D45A1E600>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/a6c86a5850e40bb9ce5527c870fbafd5