[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000018C7DD1B770>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/a58e909a1d6a2ca772e664dbeeee374e
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000018C7DD1BD40>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/a58e909a1d6a2ca772e664dbeeee374e
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000018C7DD1BEF0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/a58e909a1d6a2ca772e664dbeeee374e