[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D10C9EEF90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/d54dbaed0f7cb0cfe8cb8bc4c3552f70
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D10C9B0410>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/d54dbaed0f7cb0cfe8cb8bc4c3552f70
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D10C9EF2C0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/d54dbaed0f7cb0cfe8cb8bc4c3552f70