[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000199F9DC0F50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/dc4ed0b9-5e9b-4fc1-874a-1453efaa1525
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000199F9D179E0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/dc4ed0b9-5e9b-4fc1-874a-1453efaa1525
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000199F9DFBC50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/dc4ed0b9-5e9b-4fc1-874a-1453efaa1525