[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000017F197E5010>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/0e849f74-28da-4796-b962-e2c10bd62cad
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000017F197E4E90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/0e849f74-28da-4796-b962-e2c10bd62cad
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000017F197E50D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/0e849f74-28da-4796-b962-e2c10bd62cad