[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C601B6F290>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/13e648e19b8aa83610b28f1e50022d53
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C601B6F680>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/13e648e19b8aa83610b28f1e50022d53
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C601B6F7D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/13e648e19b8aa83610b28f1e50022d53